---
# file: roles/postgis/tasks/main.yml
- name: packages install
  apt: name={{item}} state=present
  with_items:
    - postgresql
    - postgresql-9.3-postgis-2.1
    - postgis
    - osm2pgsql
    - gis-osm

- name: pg_hba.conf settings
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=640
  notify: postgresql restart

- name: postgresql start
  service: name=postgresql state=started enabled=yes

- name: check gis database
  command: psql -U postgres -l
  register: check_gis_database
  failed_when: check_gis_database.rc not in [0,1,2]
  changed_when: check_gis_database.stdout.find('gis') == -1

- name: copy osm file
  copy: src={{osm_file}} dest=/tmp
  when: check_gis_database.stdout.find('gis') == -1

- name: import osm
  command: osm2pgsql -U postgres --slim -C 1500 /tmp/{osm_file}}
  when: check_gis_database.stdout.find('gis') == -1

- debug: var=check_gis_database

- debug: var=check_gis_database.stdout.find('gis')